INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the fish say when it hit the wall?','Dam.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you make a tissue dance?','You put a little boogie on it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s Forrest Gump\'s password?','1Forrest1');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a belt made out of watches?','A waist of time.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why can\'t bicycles stand on their own?','They are two tired');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does a train eat?','It goes chew, chew');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a singing Laptop','A Dell');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many lips does a flower have?','Tulips');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you organize an outer space party?','You planet');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of shoes does a thief wear?','Sneakers');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the best time to go to the dentist?','Tooth hurty.');
INSERT INTO joke(typeId,setup,punchline) VALUES (4,'Knock knock. \n Who\'s there? \n A broken pencil. \n A broken pencil who?','Never mind. It\'s pointless.');
INSERT INTO joke(typeId,setup,punchline) VALUES (4,'Knock knock. \n Who\'s there? \n Cows go. \n Cows go who?','No, cows go moo.');
INSERT INTO joke(typeId,setup,punchline) VALUES (4,'Knock knock. \n Who\'s there? \n Little old lady. \n Little old lady who?','I didn\'t know you could yodel!');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What\'s the best thing about a Boolean?','Even if you\'re wrong, you\'re only off by a bit.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What\'s the object-oriented way to become wealthy?','Inheritance');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Where do programmers like to hangout?','The Foo Bar.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why did the programmer quit his job?','Because he didn\'t get arrays.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the two silk worms in a race?','It ended in a tie.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a laughing motorcycle?','A Yamahahahaha.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'A termite walks into a bar and says...','\'Where is the bar tended?\'');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What does C.S. Lewis keep at the back of his wardrobe?','Narnia business!');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why do programmers always mix up Halloween and Christmas?','Because Oct 31 == Dec 25');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'A SQL query walks into a bar, walks up to two tables and asks...','\'Can I join you?\'');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'How many programmers does it take to change a lightbulb?','None that\'s a hardware problem');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program','the rest of them will write Perl');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'[\'hip\', \'hip\']','(hip hip array)');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'To understand what recursion is...','You must first understand what recursion is');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'There are 10 types of people in this world...','Those who understand binary and those who don\'t');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the duck say when he bought lipstick?','Put it on my bill');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What happens to a frog\'s car when it breaks down?','It gets toad away');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'did you know the first French fries weren\'t cooked in France?','they were cooked in Greece');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Which song would an exception sing?','Can\'t catch me - Avicii');
INSERT INTO joke(typeId,setup,punchline) VALUES (4,'Knock knock. \n Who\'s there? \n Opportunity.','That is impossible. Opportunity doesn’t come knocking twice!');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why do Java programmers wear glasses?','Because they don\'t C#');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the mushroom get invited to the party?','Because he was a fungi.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Do you know what the word \'was\' was initially?','Before was was was was was is.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I\'m reading a book about anti-gravity...','It\'s impossible to put down');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'If you\'re American when you go into the bathroom, and American when you come out, what are you when you\'re in there?','European');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Want to hear a joke about a piece of paper?','Never mind...it\'s tearable');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I just watched a documentary about beavers.','It was the best dam show I ever saw');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'If you see a robbery at an Apple Store...','Does that make you an iWitness?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'A ham sandwhich walks into a bar and orders a beer. The bartender says...','I\'m sorry, we don\'t serve food here');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the Clydesdale give the pony a glass of water?','Because he was a little horse');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'If you boil a clown...','Do you get a laughing stock?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Finally realized why my plant sits around doing nothing all day...','He loves his pot.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Don\'t look at the eclipse through a colander.','You\'ll strain your eyes.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I bought some shoes from a drug dealer.','I don\'t know what he laced them with, but I was tripping all day!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do chicken coops only have two doors?','Because if they had four, they would be chicken sedans');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a factory that sells passable products?','A satisfactory');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'When a dad drives past a graveyard: Did you know that\'s a popular cemetery?','Yep, people are just dying to get in there');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the invisible man turn down the job offer?','He couldn\'t see himself doing it');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you make holy water?','You boil the hell out of it');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I had a dream that I was a muffler last night.','I woke up exhausted!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why is peter pan always flying?','Because he neverlands');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'How do you check if a webpage is HTML5?','Try it out on Internet Explorer');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a cow with no legs?','Ground beef!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I dropped a pear in my car this morning.','You should drop another one, then you would have a pair.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Lady: How do I spread love in this cruel world?','Random Dude: [...💘]');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'A user interface is like a joke.','If you have to explain it then it is not that good.');
INSERT INTO joke(typeId,setup,punchline) VALUES (4,'Knock knock. \n Who\'s there? \n Hatch. \n Hatch who?','Bless you!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call sad coffee?','Despresso.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the butcher work extra hours at the shop?','To make ends meat.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the hungry clock?','It went back four seconds.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Well...','That’s a deep subject.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear the story about the cheese that saved the world?','It was legend dairy.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you watch the new comic book movie?','It was very graphic!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I started a new business making yachts in my attic this year...','The sails are going through the roof.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I got hit in the head by a soda can, but it didn\'t hurt that much...','It was a soft drink.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I can\'t tell if i like this blender...','It keeps giving me mixed results.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I couldn\'t get a reservation at the library...','They were fully booked.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'I was gonna tell you a joke about UDP...','...but you might not get it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'The punchline often arrives before the set-up.','Do you know the problem with UDP jokes?');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why do C# and Java developers keep breaking their keyboards?','Because they use a strongly typed language.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you give to a lemon in need?','Lemonaid.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Never take advice from electrons.','They are always negative.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Hey, dad, did you get a haircut?','No, I got them all cut.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What time is it?','I don\'t know... it keeps changing.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'A weasel walks into a bar. The bartender says, \"Wow, I\'ve never served a weasel before. What can I get for you?\"','Pop,goes the weasel.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Bad at golf?','Join the club.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Can a kangaroo jump higher than the Empire State Building?','Of course. The Empire State Building can\'t jump.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Can February march?','No, but April may.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Can I watch the TV?','Yes, but don’t turn it on.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Dad, can you put my shoes on?','I don\'t think they\'ll fit me.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the bread factory burning down?','They say the business is toast.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the chameleon who couldn\'t change color?','They had a reptile dysfunction.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the cheese factory that exploded in France?','There was nothing left but de Brie.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the cow who jumped over the barbed wire fence?','It was udder destruction.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the guy who invented Lifesavers?','They say he made a mint.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the guy whose whole left side was cut off?','He\'s all right now.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the kidnapping at school?','It\'s ok, he woke up.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the Mexican train killer?','He had loco motives');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the new restaurant on the moon?','The food is great, but there’s just no atmosphere.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the runner who was criticized?','He just took it in stride');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the scientist who was lab partners with a pot of boiling water?','He had a very esteemed colleague.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear about the submarine industry?','It really took a dive...');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear that David lost his ID in prague?','Now we just have to call him Dav.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear that the police have a warrant out on a midget psychic ripping people off?','It reads \"Small medium at large.\"');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear the joke about the wandering nun?','She was a roman catholic.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear the news?','FedEx and UPS are merging. They’re going to go by the name Fed-Up from now on.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you hear the one about the guy with the broken hearing aid?','Neither did he.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you know crocodiles could grow up to 15 feet?','But most just have 4.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do ghosts call their true love?','Their ghoul-friend');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you know that protons have mass?','I didn\'t even know they were catholic.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Did you know you should always take an extra pair of pants golfing?','Just in case you get a hole in one.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Do I enjoy making courthouse puns?','Guilty');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Do you know where you can get chicken broth in bulk?','The stock market.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Do you want a brief explanation of what an acorn is?','In a nutshell, it\'s an oak tree.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Ever wondered why bees hum?','It\'s because they don\'t know the words.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Have you ever heard of a music group called Cellophane?','They mostly wrap.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Have you heard of the band 1023MB?','They haven\'t got a gig yet.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Have you heard the rumor going around about butter?','Never mind, I shouldn\'t spread it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How are false teeth like stars?','They come out at night!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How can you tell a vampire has a cold?','They start coffin.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How come a man driving a train got struck by lightning?','He was a good conductor.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How come the stadium got hot after the game?','Because all of the fans left.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How did Darth Vader know what Luke was getting for Christmas?','He felt his presents.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How did the hipster burn the roof of his mouth?','He ate the pizza before it was cool.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do hens stay fit?','They always egg-cercise!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do locomotives know where they\'re going?','Lots of training');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do the trees get on the internet?','They log on.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you find Will Smith in the snow?','Look for fresh prints.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you fix a broken pizza?','With tomato paste.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you fix a damaged jack-o-lantern?','You use a pumpkin patch.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you get a baby alien to sleep?','You rocket.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you get two whales in a car?','Start in England and drive West.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you know if there’s an elephant under your bed?','Your head hits the ceiling!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you make a hankie dance?','Put a little boogie in it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How good are you at Power Point?','I Excel at it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you organize a space party?','You planet.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you steal a coat?','You jacket.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you tell the difference between a crocodile and an alligator?','You will see one later and one in a while.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does a dyslexic poet write?','Inverse.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does a French skeleton say hello?','Bone-jour.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does a penguin build it’s house?','Igloos it together.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does a scientist freshen their breath?','With experi-mints!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How does the moon cut his hair?','Eclipse it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many apples grow on a tree?','All of them!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many bones are in the human hand?','A handful of them.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many hipsters does it take to change a lightbulb?','Oh, it\'s a really obscure number. You\'ve probably never heard of it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many kids with ADD does it take to change a lightbulb?','Let\'s go ride bikes!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many optometrists does it take to change a light bulb?','1 or 2? 1... or 2?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many seconds are in a year?','12. January 2nd, February 2nd, March 2nd, April 2nd.... etc');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many South Americans does it take to change a lightbulb?','A Brazilian');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How many tickles does it take to tickle an octopus?','Ten-tickles!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How much does a hipster weigh?','An instagram.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How was the snow globe feeling after the storm?','A little shaken.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Is the pool safe for diving?','It deep ends.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Is there a hole in your shoe?','No… Then how’d you get your foot in it?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the spaghetti say to the other spaghetti?','Pasta la vista, baby!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s 50 Cent’s name in Zimbabwe?','200 Dollars.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Want to hear a chimney joke?','Got stacks of em! First one\'s on the house');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Want to hear a joke about construction?','Nah, I\'m still working on it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Want to hear my pizza joke?','Never mind, it\'s too cheesy.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What animal is always at a game of cricket?','A bat.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What are the strongest days of the week?','Saturday and Sunday...the rest are weekdays.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What biscuit does a short person like?','Shortbread.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What cheese can never be yours?','Nacho cheese.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What creature is smarter than a talking parrot?','A spelling bee.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did celery say when he broke up with his girlfriend?','She wasn\'t right for me, so I really don\'t carrot all.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did Michael Jackson name his denim store?','Billy Jeans!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did one nut say as he chased another nut?','I\'m a cashew!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did one plate say to the other plate?','Dinner is on me!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did one snowman say to the other snow man?','Do you smell carrot?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did one wall say to the other wall?','I\'ll meet you at the corner!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did Romans use to cut pizza before the rolling cutter was invented?','Lil Caesars');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the 0 say to the 8?','Nice belt.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the beaver say to the tree?','It\'s been nice gnawing you.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the big flower say to the littler flower?','Hi, bud!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the Buffalo say to his little boy when he dropped him off at school?','Bison.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the digital clock say to the grandfather clock?','Look, no hands!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the dog say to the two trees?','Bark bark.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the Dorito farmer say to the other Dorito farmer?','Cool Ranch!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the fish say when it swam into a wall?','Damn!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the grape do when he got stepped on?','He let out a little wine.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the judge say to the dentist?','Do you swear to pull the tooth, the whole tooth and nothing but the tooth?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the late tomato say to the early tomato?','I’ll ketch up');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the left eye say to the right eye?','Between us, something smells!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the mountain climber name his son?','Cliff.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the ocean say to the beach?','Thanks for all the sediment.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the ocean say to the shore?','Nothing, it just waved.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why don\'t you find hippopotamuses hiding in trees?','They\'re really good at it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the pirate say on his 80th birthday?','Aye Matey!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the Red light say to the Green light?','Don\'t look at me I\'m changing!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the scarf say to the hat?','You go on ahead, I am going to hang around a bit longer.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the shy pebble wish for?','That she was a little boulder.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the traffic light say to the car as it passed?','Don\'t look I\'m changing!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What did the Zen Buddist say to the hotdog vendor?','Make me one with everything.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do birds give out on Halloween?','Tweets.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do I look like?','A JOKE MACHINE!?');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do prisoners use to call each other?','Cell phones.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do vegetarian zombies eat?','Grrrrrainnnnnssss.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a bear with no teeth?','A gummy bear!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a bee that lives in America?','A USB.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a boomerang that won\'t come back?','A stick.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a careful wolf?','Aware wolf.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a cow on a trampoline?','A milk shake!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a cow with no legs?','Ground beef.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a cow with two legs?','Lean beef.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a crowd of chess players bragging about their wins in a hotel lobby?','Chess nuts boasting in an open foyer.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a dad that has fallen through the ice?','A Popsicle.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a dictionary on drugs?','High definition.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'what do you call a dog that can do magic tricks?','a labracadabrador');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a droid that takes the long way around?','R2 detour.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a duck that gets all A\'s?','A wise quacker.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a fake noodle?','An impasta.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a fashionable lawn statue with an excellent sense of rhythmn?','A metro-gnome');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a fat psychic?','A four-chin teller.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a fly without wings?','A walk.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a girl between two posts?','Annette.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a group of disorganized cats?','A cat-tastrophe.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a group of killer whales playing instruments?','An Orca-stra.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a monkey in a mine field?','A babooooom!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a nervous javelin thrower?','Shakespeare.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a pig that knows karate?','A pork chop!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a pig with three eyes?','Piiig');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a pile of cats?','A Meowtain.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a sheep with no legs?','A cloud.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a troublesome Canadian high schooler?','A poutine.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call an alligator in a vest?','An in-vest-igator!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call an Argentinian with a rubber toe?','Roberto');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call an eagle who can play the piano?','Talonted!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call an elephant that doesn’t matter?','An irrelephant.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call an old snowman?','Water.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call cheese by itself?','Provolone.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call corn that joins the army?','Kernel.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call someone with no nose?','Nobody knows.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call two barracuda fish?','A Pairacuda!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you do on a remote island?','Try and find the TV island it belongs to.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you do when you see a space man?','Park your car, man.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you get hanging from Apple trees?','Sore arms.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you get when you cross a bee and a sheep?','A bah-humbug.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you get when you cross a chicken with a skunk?','A fowl smell!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you get when you cross a rabbit with a water hose?','Hare spray.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you get when you cross a snowman with a vampire?','Frostbite.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you give a sick lemon?','Lemonaid.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What does a clock do when it\'s hungry?','It goes back four seconds!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What does a female snake use for support?','A co-Bra!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What does a pirate pay for his corn?','A buccaneer!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What does an angry pepper do?','It gets jalapeño face.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What happens to a frog\'s car when it breaks down?','It gets toad.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What happens when you anger a brain surgeon?','They will give you a piece of your mind.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What has ears but cannot hear?','A field of corn.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is a centipedes\'s favorite Beatle song?','I want to hold your hand, hand, hand, hand...');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is a tornado\'s favorite game to play?','Twister!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is a vampire\'s favorite fruit?','A blood orange.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is a witch\'s favorite subject in school?','Spelling!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is red and smells like blue paint?','Red paint!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is the difference between ignorance and apathy?','I don\'t know and I don\'t care.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is the hardest part about sky diving?','The ground.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is the leading cause of dry skin?','Towels');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is the least spoken language in the world?','Sign Language');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is the tallest building in the world?','The library, it’s got the most stories!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What is this movie about?','It is about 2 hours long.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of award did the dentist receive?','A little plaque.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of bagel can fly?','A plain bagel.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of dinosaur loves to sleep?','A stega-snore-us.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of dog lives in a particle accelerator?','A Fermilabrador Retriever.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of magic do cows believe in?','MOODOO.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of music do planets listen to?','Nep-tunes.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of pants do ghosts wear?','Boo jeans.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of tree fits in your hand?','A palm tree!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What lies at the bottom of the ocean and twitches?','A nervous wreck.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What musical instrument is found in the bathroom?','A tuba toothpaste.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What time did the man go to the dentist?','Tooth hurt-y.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What type of music do balloons hate?','Pop music!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What was a more important invention than the first telephone?','The second one.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What was the pumpkin’s favorite sport?','Squash.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s black and white and read all over?','The newspaper.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s blue and not very heavy?','Light blue.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s brown and sticky?','A stick.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s orange and sounds like a parrot?','A Carrot.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s red and bad for your teeth?','A Brick.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the best thing about elevator jokes?','They work on so many levels.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the difference between a guitar and a fish?','You can tune a guitar but you can\'t \"tuna\"fish!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the difference between a hippo and a zippo?','One is really heavy, the other is a little lighter.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the difference between a seal and a sea lion?','An ion!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the worst part about being a cross-eyed teacher?','They can\'t control their pupils.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What\'s the worst thing about ancient history class?','The teachers tend to Babylon.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s brown and sounds like a bell?','Dung!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s E.T. short for?','He’s only got little legs.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s Forest Gump’s Facebook password?','1forest1');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s the advantage of living in Switzerland?','Well, the flag is a big plus.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What’s the difference between an African elephant and an Indian elephant?','About 5000 miles.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'When do doctors get angry?','When they run out of patients.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'When does a joke become a dad joke?','When it becomes apparent.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'When is a door not a door?','When it\'s ajar.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where did you learn to make ice cream?','Sunday school.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do bees go to the bathroom?','The BP station.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do hamburgers go to dance?','The meat-ball.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do rabbits go after they get married?','On a bunny-moon.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do sheep go to get their hair cut?','The baa-baa shop.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do you learn to make banana splits?','At sundae school.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where do young cows eat lunch?','In the calf-ateria.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where does batman go to the bathroom?','The batroom.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where does Fonzie like to go for lunch?','Chick-Fil-Eyyyyyyyy.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where does Napoleon keep his armies?','In his sleevies.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where was the Declaration of Independence signed?','At the bottom!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Where’s the bin?','I haven’t been anywhere!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Which side of the chicken has more feathers?','The outside.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Who did the wizard marry?','His ghoul-friend');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Who is the coolest Doctor in the hospital?','The hip Doctor!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are fish easy to weigh?','Because they have their own scales.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are fish so smart?','Because they live in schools!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are ghosts bad liars?','Because you can see right through them!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are graveyards so noisy?','Because of all the coffin.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are mummys scared of vacation?','They\'re afraid to unwind.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are oranges the smartest fruit?','Because they are made to concentrate.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are pirates called pirates?','Because they arrr!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are skeletons so calm?','Because nothing gets under their skin.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why can\'t a bicycle stand on its own?','It\'s two-tired.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why can\'t you use \"Beef stew\"as a password?','Because it\'s not stroganoff.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why can\'t your nose be 12 inches long?','Because then it\'d be a foot!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why can’t you hear a pterodactyl go to the bathroom?','The p is silent.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why couldn\'t the kid see the pirate movie?','Because it was rated arrr!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why couldn\'t the lifeguard save the hippie?','He was too far out, man.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did Dracula lie in the wrong coffin?','He made a grave mistake.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did Sweden start painting barcodes on the sides of their battleships?','So they could Scandinavian.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the A go to the bathroom and come out as an E?','Because he had a vowel movement.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the barber win the race?','He took a short cut.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the belt go to prison?','He held up a pair of pants!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the burglar hang his mugshot on the wall?','To prove that he was framed!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the chicken get a penalty?','For fowl play.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the Clydesdale give the pony a glass of water?','Because he was a little horse!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the coffee file a police report?','It got mugged.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the cookie cry?','Because his mother was a wafer so long');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the cookie cry?','It was feeling crumby.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the cowboy have a weiner dog?','Somebody told him to get a long little doggy.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the fireman wear red, white, and blue suspenders?','To hold his pants up.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the girl smear peanut butter on the road?','To go with the traffic jam.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the half blind man fall in the well?','Because he couldn\'t see that well!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the house go to the doctor?','It was having window panes.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the kid cross the playground?','To get to the other slide.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the man put his money in the freezer?','He wanted cold hard cash!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the man run around his bed?','Because he was trying to catch up on his sleep!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the melons plan a big wedding?','Because they cantaloupe!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the octopus beat the shark in a fight?','Because it was well armed.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the opera singer go sailing?','They wanted to hit the high Cs.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the scarecrow win an award?','Because he was outstanding in his field.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the tomato blush?','Because it saw the salad dressing.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the tree go to the dentist?','It needed a root canal.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the worker get fired from the orange juice factory?','Lack of concentration.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why didn\'t the number 4 get into the nightclub?','Because he is 2 square.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why didn’t the orange win the race?','It ran out of juice.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why didn’t the skeleton cross the road?','Because he had no guts.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do bananas have to put on sunscreen before they go to the beach?','Because they might peel!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do bears have hairy coats?','Fur protection.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do bees have sticky hair?','Because they use honey combs!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do bees hum?','Because they don\'t know the words.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do birds fly south for the winter?','Because it\'s too far to walk.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do choirs keep buckets handy?','So they can carry their tune');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do crabs never give to charity?','Because they’re shellfish.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do ducks make great detectives?','They always quack the case.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do mathematicians hate the U.S.?','Because it\'s indivisible.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do pirates not know the alphabet?','They always get stuck at \"C\".');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do pumpkins sit on people’s porches?','They have no hands to knock on the door.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do scuba divers fall backwards into the water?','Because if they fell forwards they’d still be in the boat.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do trees seem suspicious on sunny days?','Dunno, they\'re just a bit shady.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do valley girls hang out in odd numbered groups?','Because they can\'t even.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do wizards clean their teeth three times a day?','To prevent bat breath!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why do you never see elephants hiding in trees?','Because they\'re so good at it.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does a chicken coop only have two doors?','Because if it had four doors it would be a chicken sedan.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does a Moon-rock taste better than an Earth-rock?','Because it\'s a little meteor.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base?','Because there’s a Shortstop in between!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does Norway have barcodes on their battleships?','So when they get back to port, they can Scandinavian.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does Superman get invited to dinners?','Because he is a Supperhero.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does Waldo only wear stripes?','Because he doesn\'t want to be spotted.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Knock-knock.','A race condition. Who is there?');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What\'s the best part about TCP jokes?','I get to keep telling them until you get them.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'A programmer puts two glasses on his bedside table before going to sleep.','A full one, in case he gets thirsty, and an empty one, in case he doesn’t.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'There are 10 kinds of people in this world.','Those who understand binary, those who don\'t, and those who weren\'t expecting a base 3 joke.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Two guys walk into a bar . . .','The first guy says \"Ouch!\" and the second says \"Yeah, I didn\'t see it either.\"');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What did the router say to the doctor?','It hurts when IP.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'An IPv6 packet is walking out of the house.','He goes nowhere.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'A DHCP packet walks into a bar and asks for a beer.','Bartender says, \"here, but I’ll need that back in an hour!\"');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'3 SQL statements walk into a NoSQL bar. Soon, they walk out','They couldn\'t find a table.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'I saw a nice stereo on Craigslist for $1. Seller says the volume is stuck on ‘high’','I couldn’t turn it down.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What’s the object-oriented way to become wealthy?','Inheritance.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a bee that can\'t make up its mind?','A maybe.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why was Cinderalla thrown out of the football team?','Because she ran away from the ball.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What kind of music do welders like?','Heavy metal.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why are “Dad Jokes” so good?','Because the punchline is apparent.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Java developers wear glasses.','Because they can\'t C#.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why dot net developers don\'t wear glasses?','Because they see sharp.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why is seven bigger than nine?','Because seven ate nine.');
INSERT INTO joke(typeId,setup,punchline) VALUES (3,'Why do fathers take an extra pair of socks when they go golfing?','In case they get a hole in one!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'What do you call a suspicious looking laptop?','Asus');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What did the Java code say to the C code?','You\'ve got no class.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What is the most used language in programming?','Profanity.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Why do programmers always get Christmas and Halloween mixed up?','Because DEC 25 = OCT 31');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'What goes after USA?','USB.');
INSERT INTO joke(typeId,setup,punchline) VALUES (3,'Why don\'t eggs tell jokes?','Because they would crack each other up.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'How do you make the number one disappear?','Add the letter G and it’s “gone”!');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'My older brother always tore the last pages of my comic books, and never told me why.','I had to draw my own conclusions.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'The Sergeant-Major growled at the young soldier: I didn’t see you at camouflage training this morning.','Thank you very much, sir.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why does Waldo only wear stripes?','Because he doesn\'t want to be spotted.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'A male developer often gets called as a Dev, then what would you call a female developer?.','Devi.');
INSERT INTO joke(typeId,setup,punchline) VALUES (1,'Why did the kid throw the watch out the window?','So time would fly.');
INSERT INTO joke(typeId,setup,punchline) VALUES (2,'Where did the API go to eat?','To the RESTaurant.');
INSERT INTO joke(typeId,setup,punchline) VALUES (5,'Why did the rooster cross the road?','He heard that the chickens at KFC were pretty hot.');
